# Analyzing Data for Rotational Churners

## Agendas:
 - Fix mock data creation.
 - Convert everything in this notebook to callable functions/script.
 - visualizations

Loading the churner data and data of the newer/more recent users

In [1]:
import numpy as np
import pandas as pd

dfs = pd.ExcelFile('data/mock/sample_mock_c_data.xlsx')
sheets = dfs.sheet_names
d = []
for i in range(10):
    d.append(dfs.parse(sheet_name=sheets[i]))

newer_users = pd.read_excel('data/mock/sample_mock_rc_data.xlsx')

In [2]:
d[0].head()

weeks             IMEI  phone_nums  credits_loaded_per_week  \
0 2018-04-17  772605788289199  9369298671                       20   
1 2018-04-24  772605788289199  9369298671                      800   
2 2018-05-01  772605788289199  9369298671                       30   
3 2018-05-08  772605788289199  9369298671                      800   
4 2018-05-15  772605788289199  9369298671                        0   

   num_hrs_spend_on_net  mobile_data_usage(gb)  promos_used  active_times  \
0                  17.9                   7.51            7             2   
1                   1.1                   5.55            0             2   
2                  20.1                   6.78            8             2   
3                  12.9                   8.65            7             1   
4                  14.8                   7.28            3             0   

   activity_status  
0                0  
1                0  
2                0  
3                0  
4                0

In [3]:
newer_users.head()

weeks              IMEI  phone_nums  credits_loaded_per_week  \
0 2018-12-11  5969775737476310  9995451837                       50   
1 2018-12-18  5969775737476310  9995451837                     1000   
2 2018-12-25  5969775737476310  9995451837                       70   
3 2019-01-01  5969775737476310  9995451837                     1000   
4 2019-01-08  5969775737476310  9995451837                        0   

   num_hrs_spend_on_net  mobile_data_usage(gb)  promos_used  active_times  \
0                  19.2                    7.5            9             0   
1                   1.1                    4.0            1             2   
2                  20.1                    6.8            7             2   
3                  12.1                    6.7            5             1   
4                  14.8                    7.7            2             1   

   activity_status  
0                0  
1                0  
2                0  
3                0  
4                0

#### Using Euclidean Distance to Compare how Similar 2 the New User is to a Churner

In [4]:
def Euclidean_Dist(df1, df2, cols=d[0].columns[3:-3]):
    return (np.linalg.norm(df1[cols].values - df2[cols].values, axis=1))

In [5]:
df1 = d[0].iloc[:-4, :-3]
df2 = newer_users.iloc[:len(df1), :-3]
df3 = d[3].iloc[:len(df1), :-3]
print(len(df1), ' ', len(df2), ' ', len(df3))

29   29   29


In [6]:
df1

weeks             IMEI  phone_nums  credits_loaded_per_week  \
0  2018-04-17  772605788289199  9369298671                       20   
1  2018-04-24  772605788289199  9369298671                      800   
2  2018-05-01  772605788289199  9369298671                       30   
3  2018-05-08  772605788289199  9369298671                      800   
4  2018-05-15  772605788289199  9369298671                        0   
5  2018-05-22  772605788289199  9369298671                        0   
6  2018-05-29  772605788289199  9369298671                      200   
7  2018-06-05  772605788289199  9369298671                       90   
8  2018-06-12  772605788289199  9369298671                        0   
9  2018-06-19  772605788289199  9369298671                        0   
10 2018-06-26  772605788289199  9369298671                      150   
11 2018-07-03  772605788289199  9369298671                       90   
12 2018-07-10  772605788289199  9369298671                        0   
13 2018-07-17  772605788289199  9369298671                        0   
14 2018-07-24  772605788289199  9369298671                       20   
15 2018-07-31  772605788289199  9369298671                        0   
16 2018-08-07  772605788289199  9369298671                        0   
17 2018-08-14  772605788289199  9369298671                       50   
18 2018-08-21  772605788289199  9369298671                      300   
19 2018-08-28  772605788289199  9369298671                        0   
20 2018-09-04  772605788289199  9369298671                       90   
21 2018-09-11  772605788289199  9369298671                      150   
22 2018-09-18  772605788289199  9369298671                        0   
23 2018-09-25  772605788289199  9369298671                        0   
24 2018-10-02  772605788289199  9369298671                       30   
25 2018-10-09  772605788289199  9369298671                       70   
26 2018-10-16  772605788289199  9369298671                      300   
27 2018-10-23  772605788289199  9369298671                      500   
28 2018-10-30  772605788289199  9369298671                        0   

    num_hrs_spend_on_net  mobile_data_usage(gb)  
0                   17.9                   7.51  
1                    1.1                   5.55  
2                   20.1                   6.78  
3                   12.9                   8.65  
4                   14.8                   7.28  
5                    8.0                   6.59  
6                   22.3                   5.11  
7                   11.7                   6.51  
8                   11.6                   5.98  
9                   19.3                   7.22  
10                  22.3                   6.79  
11                   4.9                   6.33  
12                  17.4                   6.11  
13                  19.9                   8.85  
14                  10.7                   7.82  
15                  11.0                   8.43  
16                  21.5                   8.60  
17                  20.6                   5.82  
18                   1.0                   7.02  
19                   8.2                   5.16  
20                   9.3                   7.37  
21                   4.6                   6.98  
22                   8.4                   7.53  
23                  18.8                   7.88  
24                   2.0                   7.07  
25                  15.1                   8.65  
26                   1.7                   5.31  
27                  22.2                   8.20  
28                  10.5                   8.58

In [7]:
distances = Euclidean_Dist(df1, df2)
distances

array([3.00281551e+01, 2.00006006e+02, 4.00000050e+01, 2.00011106e+02,
       4.20000000e-01, 3.00331167e+01, 8.00001379e+02, 9.10000811e+02,
       9.20000000e-01, 2.68000000e+00, 5.00143989e+01, 2.00000225e+01,
       3.01935771e+01, 2.61007663e+00, 9.80000862e+02, 1.10040901e+00,
       1.80277564e+00, 9.50002981e+02, 7.00003959e+02, 1.50053324e+00,
       9.10002831e+02, 5.00636435e+01, 2.00090205e+01, 1.68237927e+00,
       3.01552798e+01, 9.30003098e+02, 1.50000000e+02, 3.00004817e+02,
       2.58000000e+00])

In [8]:
distances.mean()

253.3045256480743

In [9]:
# comparing it to another user who is not related
distances1 = Euclidean_Dist(df2, df3)
distances1

array([  30.09007311, 1000.01516334,   50.71197985,  950.00601203,
          8.62160658,   31.66172611, 1000.01957086, 1000.02617411,
          2.50008   ,    7.2510413 ,  100.69451028,   81.05189449,
         30.9141149 ,   17.67399219, 1000.00388144,    5.970335  ,
         10.40461917,  910.16896761,  950.09294893,    8.17273516,
        200.30027459,   70.46020153,   22.08241155,    1.13507709,
         17.37475467, 1000.10919609,   60.66125287,  500.10574492,
          3.80426077])

In [10]:
distances1.mean()

312.8305034665228

### As we can see, the new user is much more similar to churner 1 compared to churner 2 when using euclidean distance.

In [11]:
df1_sums = df1.groupby('IMEI')[d[0].columns[3:-3]].sum()
df2_sums = df2.groupby('IMEI')[d[0].columns[3:-3]].sum()
df3_sums = df3.groupby('IMEI')[d[0].columns[3:-3]].sum()

In [12]:
# Modifying the Euchlidean Distance function
def Mod_Euclidean_Dist(df1,df2,cols=d[0].columns[3:-3]):
    x = df1.groupby('IMEI')[cols].sum()
    y = df2.groupby('IMEI')[cols].sum()

    return np.linalg.norm(x.values - y.values,
                   axis=1)

In [13]:
mod_distances = Mod_Euclidean_Dist(df1,df2)
mod_distances 

# the first euclidean distance result produced a much better result in terms of comparing the difference of the 2 dataframes

array([6730.01072454])

### Different Computation Approach for Comparing

Computation:
 - a = list of sums in each column of df1
 - b = list of sums in each column of df2
 - c = l/h (list of similarities per column; l = lower value in a certain index of lists a and b; h = higher value)

 similarity = (sum(c)/len(c))*100

In [14]:
def average_similarity(df1_sums, df2_sums):
    percent_sim = []

    for i in range(len(df1_sums.columns.tolist())):
        x = 0
        y = 0
        if df1_sums[df1_sums.columns.tolist()[i]].tolist() < df2_sums[df2_sums.columns.tolist()[i]].tolist():
            x = df1_sums[df1_sums.columns.tolist()[i]].tolist()[0]
            y = df2_sums[df2_sums.columns.tolist()[i]].tolist()[0]
        else:
            x = df2_sums[df2_sums.columns.tolist()[i]].tolist()[0]
            y = df1_sums[df1_sums.columns.tolist()[i]].tolist()[0]
        percent_sim.append(x/y)
        
    return percent_sim

In [15]:
df1_sums

credits_loaded_per_week  num_hrs_spend_on_net  \
IMEI                                                             
772605788289199                     3690                 369.8   

                 mobile_data_usage(gb)  
IMEI                                    
772605788289199                 205.68

In [16]:
df2_sums

credits_loaded_per_week  num_hrs_spend_on_net  \
IMEI                                                              
5969775737476310                    10420                 378.6   

                  mobile_data_usage(gb)  
IMEI                                     
5969775737476310                  197.5

In [17]:
df3_sums

credits_loaded_per_week  num_hrs_spend_on_net  \
IMEI                                                             
376328182885989                     1600                 348.1   

                 mobile_data_usage(gb)  
IMEI                                    
376328182885989                 203.34

In [18]:
av1 = average_similarity(df1_sums,df2_sums)
av2 = average_similarity(df3_sums,df2_sums)

In [19]:
ave_sim1 = sum(av1)/len(av1)*100
ave_sim2 = sum(av2)/len(av2)*100
print('Similarity is: {:.2f}%'.format(float(ave_sim1)))
print('Similarity is: {:.2f}%'.format(float(ave_sim2)))

Similarity is: 76.37%
Similarity is: 68.14%


### Computing Similarity per Row and Computing the Average Similarity

In [20]:
df1.head(3)

weeks             IMEI  phone_nums  credits_loaded_per_week  \
0 2018-04-17  772605788289199  9369298671                       20   
1 2018-04-24  772605788289199  9369298671                      800   
2 2018-05-01  772605788289199  9369298671                       30   

   num_hrs_spend_on_net  mobile_data_usage(gb)  
0                  17.9                   7.51  
1                   1.1                   5.55  
2                  20.1                   6.78

In [21]:
df2.head(3)

weeks              IMEI  phone_nums  credits_loaded_per_week  \
0 2018-12-11  5969775737476310  9995451837                       50   
1 2018-12-18  5969775737476310  9995451837                     1000   
2 2018-12-25  5969775737476310  9995451837                       70   

   num_hrs_spend_on_net  mobile_data_usage(gb)  
0                  19.2                    7.5  
1                   1.1                    4.0  
2                  20.1                    6.8

In [22]:
vals = [[],[],[],[],[]]

z=0
for i in df1.columns[3:]:
    for j in range(len(df1[i].tolist())):
        x = 0
        y = 0
        if df1[i].tolist()[j] < df2[i].tolist()[j]:
            x = df1[i].tolist()[j]
            y = df2[i].tolist()[j]
        else:
            y = df1[i].tolist()[j]
            x = df2[i].tolist()[j]
        
        if x == 0 and y == 0:
            vals[z].append(100.00)
        else:
            vals[z].append(round((x/y)*100,2))
    z+=1

# I could have just used df1['column'] / df2['column'] or df2['column'] / df1['column'], but it does not check for division by 0s.
# I also needed to check which value was lower as that will be the dividend.

In [23]:
data_dict = {}
k=0
for i in df1.columns[3:]:
    data_dict[i] = vals[k]
    k+=1

sim_df = pd.DataFrame(data_dict)

In [24]:
sim_df.head()

credits_loaded_per_week  num_hrs_spend_on_net  mobile_data_usage(gb)
0                    40.00                 93.23                  99.87
1                    80.00                100.00                  72.07
2                    42.86                100.00                  99.71
3                    80.00                 93.80                  77.46
4                   100.00                100.00                  94.55

In [25]:
sim_df['similarity'] = ((sim_df[sim_df.columns[0]] + sim_df[sim_df.columns[1]] + sim_df[sim_df.columns[2]])/300)*100
sim_df.head()

credits_loaded_per_week  num_hrs_spend_on_net  mobile_data_usage(gb)  \
0                    40.00                 93.23                  99.87   
1                    80.00                100.00                  72.07   
2                    42.86                100.00                  99.71   
3                    80.00                 93.80                  77.46   
4                   100.00                100.00                  94.55   

   similarity  
0   77.700000  
1   84.023333  
2   80.856667  
3   83.753333  
4   98.183333

In [26]:
sim_df['similarity'].mean()

76.68712643678163

### Similarity using Cosine Similarity

In [27]:
d1 = df1.iloc[:, 3:].copy()
d2 = df2.iloc[:, 3:].copy()
d3 = df3.iloc[:, 3:].copy()

d1.head()

credits_loaded_per_week  num_hrs_spend_on_net  mobile_data_usage(gb)
0                       20                  17.9                   7.51
1                      800                   1.1                   5.55
2                       30                  20.1                   6.78
3                      800                  12.9                   8.65
4                        0                  14.8                   7.28

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

cs = cosine_similarity(d1,d2)
len(cs)

29

In [29]:
len(cs[0])

29

In [30]:
# Column 4 Comparison (Rotational Churner/Same User)
test1 = [df1.iloc[:, 4].copy().tolist()]
test2 = [df2.iloc[:, 4].copy().tolist()]
test1
cosine_similarity(test1,test2)

array([[0.99769936]])

In [31]:
# Column 4 Comparison (Different User)
test1 = [df3.iloc[:, 4].copy().tolist()]
test2 = [df2.iloc[:, 4].copy().tolist()]
test1
cosine_similarity(test1,test2)

array([[0.76925831]])